### ISSUE TITLE
Syntax Error - Install All Reporting Tools

### ISSUE THREAD

**Issue by stevenhardey** [mkrupczak3/Katoolin-Robust#6]
Love the update of the tool, thank you very much.

When selecting "0" for the option "Install all Reporting Tools" an error is produced stating

> sh: 1: Syntax error: "done" unexpected (expecting "do")

I believe this is because of the missing semi-colon at line 884:
`cmd = os.system("for apackage in casefile cutycapt dos2unix dradis keepnote magictree metagoofil nipper-ng pipal do apt-get install -y $apackage; done;")`

which should say:
`cmd = os.system("for apackage in casefile cutycapt dos2unix dradis keepnote magictree metagoofil nipper-ng pipal; do apt-get install -y $apackage; done;")`

**Comment by perfectra1n** [comment]
Hey if you want to, you can do a pull request and update that line, so you get credit for fixing the issue.
He's usually pretty quick to approve pull requests.

**Comment by stevenhardey** [comment]
I have provided a pull request - #7

**Comment by stevenhardey** [comment]
I've updated my pull request as I have realised the actual issue was with the do statements not being preceeded by a semi-colon. Should all work now.
